version: '3.8'

services:

  database:
    container_name: legende_spil_db_test
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=legende_spil
    ports:
      - 15000:3306
      